POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "name": "auth-baba",
    "email": "auth-baba@email.com",
    "password": "1234567"
}

###

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "name": "auth-guru",
    "email": "auth-guru@email.com",
    "password": "1234567"
}

###

POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "name": "auth-kmaddy",
    "email": "auth-kmaddy@email.com",
    "password": "superSecretPassword"
}

###
